### ISSUE TITLE
about adding some val data 

### ISSUE THREAD

**Issue by GyoungTaeChae** [amaralibey/OpenVPRLab#2]
Hello , one more question. 

I recently got val-datasets using this repo : `https://github.com/gmberton/VPR-datasets-downloader`
However , as its' data format is not same with yours (it doesn't have gt data , instead use gps information evalutating Top k) , i cannot directly use them. 

so, i wand your advice how can i smartly integrate datasets from that repo with your work? 

thanks

**Comment by amaralibey** [comment]
Hello @GyoungTaeChae 

The goal in OpenVPRLab was to provide two validation datasets out of the box for the purpose of monitoring the model's peformance. Hence, we hardcoded the positive references (so no need for GPS coordinates).

If you want to write your own PyTorch Dataset (like `src/dataloaders/valid/mapillary_sls.py` and `src/dataloaders/valid/pittsburg.py`), just make sure the class has the following attributes:
```
dataset.num_references, # number of references in the dataset
dataset.num_queries, # number of queries
dataset.ground_truth, # most importantly, you need to provide the ground truth as a list of lists (numpy), where the ith line contains the indices of the references of the ith query.
``` 

This way, you can call them from the `_get_val_dataset()` in `src/core/vpr_datamodule.py`. This way,  the VPRFramework can use it for vaildation and show it on Tensorboard and on the Terminal.

We will sonn provide a benchmarking module, where you can test on many other datasets.

**Comment by GyoungTaeChae** [comment]
Thank you so much for your answer!
you taught me a lot!!!!
